### ISSUE TITLE
Weiterleitung bei klick auf Header Image

### ISSUE THREAD

**Issue by Matleo** [BioThemenVergabe/project#43]
Wenn man im header auf das bild oder den Textzug "Wahlsystem Biologie" klickt, wird man (egal wo man gerade ist) auf /dashboard weitergeleitet.
Von der login page sollte eine solche Weiterleitung nicht möglich sein, aus dem Admin bereich sollte zu /admin weitergeleitet werden.

**Comment by PaddaelsM** [comment]
Wird mit PHP-funktionalität später entsprechend angepasst, da Entscheidung wohin Nutzer gelangt bei Login entschieden wird. -> Weiterleitung wird dann auf / geändert.

-pm

**Comment by Matleo** [comment]
Bei click auf das Logo wird man übrigens noch auf /home weitergeleitet, was zu einem Fehler führt, da wir keine route dafür haben
