### ISSUE TITLE
[projekt] Cookie Warnung

### ISSUE THREAD

**Issue by Matleo** [BioThemenVergabe/project#54]
Laut Eiglsberger müssen wir ja eine Cookie Warnung für den Nutzer auf unseren Seiten implementieren, die so lange da bleibt, bis der user diese weg  geklickt hat.

**Comment by PaddaelsM** [comment]
Fehlt nur noch das verstecken der Meldung, wenn Bentuzer akzeptiert.

Soll Login / Registrierungsbutton solange gesperrt sein, bis cookie gesetzt ist?

**Comment by Matleo** [comment]
hmm. gute frage. solange er die cookies nicht akzeptiert, kann er sich ja  eigentlich nicht einloggen oder?
Registrieren sollte er sich schon können. aber Einloggen nicht.

**Comment by Matleo** [comment]
Wenn User cookie Meldung noch nicht akzeptiert hat und versucht sich anzumelden, dann soll bei klick auf "login" oder "registrieren" Die Cookie Meldung einmal aufblinken, oder vibrieren oder sowas.

**Comment by PaddaelsM** [comment]
Submitbuttons sind erst anklickbar, wenn User Cookiemeldung akzeptiert hat.
Hat er dieses nicht gemacht, kann er sich weder einloggen noch registrieren oder kann sonstige Funktionalität nutzen.
Meldung nimmt auch knapp 15-20% des Bildschirms ein. Einzige "andere" Lösung wäre ein Modal zu nutzen. Der Button kann zusätzlich aufgrund des gesetzten disabled-attributes gar nicht erst geklickt werden, bzw. reagiert nicht auf eine interaktion.
Sollte dies gewollt sein, bitte um Rückmeldung ansonsten ist das Issue für mich erledigt.

Optional könnten wir auch die JS Library Shepherd nutzen, welche ich recht ansprechend fände um dem nutzer zu zeigen, dass er erst die Cookiemeldung akzeptieren muss.
http://github.hubspot.com/shepherd/docs/welcome/

**Comment by Matleo** [comment]
was macht den shepherd?
Könntest du nicht auch alternativ die Cookiemeldung aufleuchten lassen, wenn der Nutzer irgendwo auf die Seite (außerhalb der Cookiemeldung) klickt?

**Comment by PaddaelsM** [comment]
Die Cookiemeldung kommt auf jeder Seite, die der Nutzer ohne Authorisierung besuchen kann. Also folgendes Routes:
- /
- /login
- /register

alle anderen routes sind durch die middleware auth geschützt.
Beschreibe das Aufleuchten bitte noch etwas genauer, was verstehst du darunter? Der "shake"-effekt wird, soweit ich das nachlesen konnte, nicht von jedem Browser unterstützt jQuery funktion effect() funktioniert irgendwie nicht - kann mich da aber gerne nochmal dran setzen.

Was Shepherd macht, kannst du ganz einfach erkennen, wenn du dem Link folgst. Man kann dadurch ein "Tutorial" einbauen, welches dem Benutzer die GUI Schrittweise erklärt.

Hierdurch könnte man dem Nutzer eben mitteilen, dass er erst die Meldung akzeptieren muss.
Ich werde Shepherd mal einbauen, damit du siehst was ich meine.
