### ISSUE TITLE
[register] Formvalidierung

### ISSUE THREAD

**Issue by PaddaelsM** [BioThemenVergabe/project#55]

**Comment by Matleo** [comment]
es muss auch überprüft werden, ob die Matrikelnummer bzw. die Email Adresse bereits in der Datenbank angelegt  wurde

**Comment by Matleo** [comment]
passwort muss bestimmte bedingungen erfüllen?
Passwort(wdh) muss mit Passwort übereinstimmen

**Comment by PaddaelsM** [comment]
Passwort-validiierung ist bei Registrierung vorhanden.
Heißt:
- Es wird überprüft, ob Password = password_confirmation
- Zeichenlänge >= 8
