### ISSUE TITLE
[Cookie] wird auch gesetzt, wenn auf welcome page "Anmeldung speichern" nicht angeklickt wird

### ISSUE THREAD

**Issue by Matleo** [BioThemenVergabe/project#57]
Dadurch wird dann der radio button auf der welcome page überflüssig oder?

**Comment by PaddaelsM** [comment]
Cookie für gespeicherte ANmeldung wird nicht gesetzt, es handelt sich hierbei um ein "einfaches" Sessionhandling welches eine Laufzeit von ca. 2 Std hat.
