### ISSUE TITLE
[/dashboard] nach login aus datenbank mit korrekten daten befüllen

### ISSUE THREAD

**Issue by Matleo** [BioThemenVergabe/project#59]
Der Nutzer, der sich einloggt, soll dann auch seine Daten auf /dashboard zu sehen bekommen.

Es geht erstmaal nur um Name matrikelnummer etc.
Wahl Daten fügen wir später hinzu.

**Comment by PaddaelsM** [comment]
Wurde soweit gemacht, wie möglich.
Kann erst beendet werden, wenn AG-Studenten Bewertung in DB steht.
- pm

**Comment by Matleo** [comment]
der zu bearbeitende teil ist erledigt
