### ISSUE TITLE
[footer] Übersetzung fertig machen

### ISSUE THREAD

**Issue by Matleo** [BioThemenVergabe/project#65]
Im Kontakbereich noch "Telefonnummer intern" und "Raum" übersetzen

und gesamten Text "über uns" übersetzen (Wenn ich dir den übersetzen soll kann ich das auch machen)

**Comment by PaddaelsM** [comment]
Muss nun besprochen werden ob Hardcodiert oder in DB hinterlegt werden soll.
Ich bin klar für's nicht hardcodierte.

**Comment by Matleo** [comment]
auf projektende geschoben
