### ISSUE TITLE
[dashboard] User soll bild hochladen können

### ISSUE THREAD

**Issue by Matleo** [BioThemenVergabe/project#71]
Bild soll dann auch in die DB gespeichert werden und beim nächsten aufruf geladen werden!

**Comment by PaddaelsM** [comment]
Benutzer kann nun Profilbild hochladen.
Es wird ein Hinweis geliefert, dass das Bild quadratisch sein sollte.
Optional hinzufügbar: Warum quadratisches Bild.
Ansonsten: close.
