### ISSUE TITLE
Willkommenstext auf Welcome-Page fließt über

### ISSUE THREAD

**Issue by Matleo** [BioThemenVergabe/project#9]
Ich hab mal einen Placeholder-Text eingefügt.
Der sollte ja eigentlich nicht überfließen, sondern der Weiße bereich für den Text sollte sich vergrößern, du kennst deinen Code besser als ich :P 
#IssuesSindGeil

**Comment by PaddaelsM** [comment]
resolve #9

style.css tag section enthält nun property display: table.
