### ISSUE TITLE
Doku

### ISSUE THREAD

**Issue by Matleo** [BioThemenVergabe/project#93]
Patrick
- Description of Visual Design 
- Advanced Characteristics of the Application
- Application Design and Implementation -> User Bereich + Welcome/Footer/Navbar + Language

Matze
- Short Description of Functionality 
- overall application architecture 
- Application Design and Implementation -> Admin Bereich

**Comment by PaddaelsM** [comment]
- [ ]  Description of Visual Design

- [ ]  Advanced Characteristics of the Application

- [ ] Application Design and Implementation

-  - [ ] User Bereich

-  - [ ] Front- /Landingpage (Welcome)

-  - [ ] Language Middleware

- [ ] Architecture -> Warum wir unsere js einzeln komprimiert haben sollten wir hier einfügen.
